"""add_idempotency_key_and_position_size_config

Revision ID: a97d74808344
Revises: 006
Create Date: 2026-01-19 19:58:22.424102
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a97d74808344"
down_revision: str | None = "006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_backtest_results_created_at"),
        "backtest_results",
        ["created_at"],
        unique=False,
    )
    op.drop_constraint(op.f("daily_stats_date_key"), "daily_stats", type_="unique")
    op.drop_index(op.f("idx_daily_stats_date"), table_name="daily_stats")
    op.create_index(op.f("ix_daily_stats_date"), "daily_stats", ["date"], unique=True)
    op.alter_column(
        "market_data",
        "price",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        comment="현재 가격 (KRW)",
        existing_comment="Current price in KRW",
        existing_nullable=False,
    )
    op.alter_column(
        "market_data",
        "volume",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        comment="24시간 누적 거래량",
        existing_comment="24-hour trading volume",
        existing_nullable=False,
    )
    op.alter_column(
        "market_data",
        "high_price",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        comment="24시간 최고가",
        existing_comment="24-hour high price",
        existing_nullable=False,
    )
    op.alter_column(
        "market_data",
        "low_price",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        comment="24시간 최저가",
        existing_comment="24-hour low price",
        existing_nullable=False,
    )
    op.alter_column(
        "market_data",
        "trade_count",
        existing_type=sa.INTEGER(),
        comment="거래 건수",
        existing_comment="Number of trades",
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_market_data_symbol"), table_name="market_data")
    op.create_index(
        op.f("ix_market_data_symbol"), "market_data", ["symbol"], unique=False
    )
    op.add_column(
        "orders",
        sa.Column(
            "idempotency_key",
            sa.String(length=64),
            nullable=True,
            comment="재시도 시 중복 방지용 키",
        ),
    )
    op.create_index(
        op.f("ix_orders_idempotency_key"), "orders", ["idempotency_key"], unique=True
    )
    op.alter_column(
        "positions",
        "symbol",
        existing_type=sa.VARCHAR(length=20),
        comment="마켓 심볼",
        existing_comment="심볼 (BTC-KRW)",
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_position_symbol"), table_name="positions")
    op.drop_constraint(op.f("positions_symbol_key"), "positions", type_="unique")
    op.create_index(op.f("ix_positions_symbol"), "positions", ["symbol"], unique=True)
    op.alter_column(
        "risk_events",
        "order_id",
        existing_type=sa.BIGINT(),
        comment="연관 주문 ID",
        existing_comment="연관 주문 ID (orders 테이블 생성 후 FK 추가)",
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_risk_event_created_at"), table_name="risk_events")
    op.drop_index(op.f("idx_risk_event_order_id"), table_name="risk_events")
    op.create_index(
        op.f("ix_risk_events_created_at"), "risk_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_risk_events_order_id"), "risk_events", ["order_id"], unique=False
    )
    op.drop_index(op.f("idx_system_config_key"), table_name="system_configs")
    op.drop_constraint(op.f("system_configs_key_key"), "system_configs", type_="unique")
    op.create_index(
        op.f("ix_system_configs_key"), "system_configs", ["key"], unique=True
    )
    op.alter_column(
        "trading_signals",
        "market_data_id",
        existing_type=sa.BIGINT(),
        comment="분석 기준 시장 데이터 ID",
        existing_comment="Reference to market data used for analysis",
        existing_nullable=True,
    )
    op.alter_column(
        "trading_signals",
        "signal_type",
        existing_type=sa.VARCHAR(length=10),
        comment="신호 타입 (BUY/HOLD/SELL)",
        existing_comment="Signal type (BUY/HOLD/SELL)",
        existing_nullable=False,
    )
    op.alter_column(
        "trading_signals",
        "confidence",
        existing_type=sa.NUMERIC(precision=3, scale=2),
        comment="신뢰도 점수 (0~1)",
        existing_comment="Confidence score (0-1)",
        existing_nullable=False,
    )
    op.alter_column(
        "trading_signals",
        "reasoning",
        existing_type=sa.TEXT(),
        comment="AI 분석 근거",
        existing_comment="AI analysis reasoning",
        existing_nullable=False,
    )
    op.alter_column(
        "trading_signals",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="신호 생성 시간",
        existing_comment="Signal creation time",
        existing_nullable=False,
    )
    op.alter_column(
        "trading_signals",
        "model_name",
        existing_type=sa.VARCHAR(length=50),
        comment="사용된 AI 모델명",
        existing_comment="AI model name used",
        existing_nullable=False,
    )
    op.alter_column(
        "trading_signals",
        "input_tokens",
        existing_type=sa.INTEGER(),
        comment="입력 토큰 수",
        existing_comment="Input tokens count",
        existing_nullable=False,
    )
    op.alter_column(
        "trading_signals",
        "output_tokens",
        existing_type=sa.INTEGER(),
        comment="출력 토큰 수",
        existing_comment="Output tokens count",
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_signal_created_at"), table_name="trading_signals")
    op.drop_index(op.f("idx_signal_market_data_id"), table_name="trading_signals")
    op.create_index(
        op.f("ix_trading_signals_created_at"),
        "trading_signals",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trading_signals_market_data_id"),
        "trading_signals",
        ["market_data_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_trading_signals_market_data_id"), table_name="trading_signals"
    )
    op.drop_index(op.f("ix_trading_signals_created_at"), table_name="trading_signals")
    op.create_index(
        op.f("idx_signal_market_data_id"),
        "trading_signals",
        ["market_data_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_signal_created_at"), "trading_signals", ["created_at"], unique=False
    )
    op.alter_column(
        "trading_signals",
        "output_tokens",
        existing_type=sa.INTEGER(),
        comment="Output tokens count",
        existing_comment="출력 토큰 수",
        existing_nullable=False,
    )
    op.alter_column(
        "trading_signals",
        "input_tokens",
        existing_type=sa.INTEGER(),
        comment="Input tokens count",
        existing_comment="입력 토큰 수",
        existing_nullable=False,
    )
    op.alter_column(
        "trading_signals",
        "model_name",
        existing_type=sa.VARCHAR(length=50),
        comment="AI model name used",
        existing_comment="사용된 AI 모델명",
        existing_nullable=False,
    )
    op.alter_column(
        "trading_signals",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Signal creation time",
        existing_comment="신호 생성 시간",
        existing_nullable=False,
    )
    op.alter_column(
        "trading_signals",
        "reasoning",
        existing_type=sa.TEXT(),
        comment="AI analysis reasoning",
        existing_comment="AI 분석 근거",
        existing_nullable=False,
    )
    op.alter_column(
        "trading_signals",
        "confidence",
        existing_type=sa.NUMERIC(precision=3, scale=2),
        comment="Confidence score (0-1)",
        existing_comment="신뢰도 점수 (0~1)",
        existing_nullable=False,
    )
    op.alter_column(
        "trading_signals",
        "signal_type",
        existing_type=sa.VARCHAR(length=10),
        comment="Signal type (BUY/HOLD/SELL)",
        existing_comment="신호 타입 (BUY/HOLD/SELL)",
        existing_nullable=False,
    )
    op.alter_column(
        "trading_signals",
        "market_data_id",
        existing_type=sa.BIGINT(),
        comment="Reference to market data used for analysis",
        existing_comment="분석 기준 시장 데이터 ID",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_system_configs_key"), table_name="system_configs")
    op.create_unique_constraint(
        op.f("system_configs_key_key"),
        "system_configs",
        ["key"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_system_config_key"), "system_configs", ["key"], unique=True
    )
    op.drop_index(op.f("ix_risk_events_order_id"), table_name="risk_events")
    op.drop_index(op.f("ix_risk_events_created_at"), table_name="risk_events")
    op.create_index(
        op.f("idx_risk_event_order_id"), "risk_events", ["order_id"], unique=False
    )
    op.create_index(
        op.f("idx_risk_event_created_at"), "risk_events", ["created_at"], unique=False
    )
    op.alter_column(
        "risk_events",
        "order_id",
        existing_type=sa.BIGINT(),
        comment="연관 주문 ID (orders 테이블 생성 후 FK 추가)",
        existing_comment="연관 주문 ID",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_positions_symbol"), table_name="positions")
    op.create_unique_constraint(
        op.f("positions_symbol_key"),
        "positions",
        ["symbol"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("idx_position_symbol"), "positions", ["symbol"], unique=True)
    op.alter_column(
        "positions",
        "symbol",
        existing_type=sa.VARCHAR(length=20),
        comment="심볼 (BTC-KRW)",
        existing_comment="마켓 심볼",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_orders_idempotency_key"), table_name="orders")
    op.drop_column("orders", "idempotency_key")
    op.drop_index(op.f("ix_market_data_symbol"), table_name="market_data")
    op.create_index(
        op.f("idx_market_data_symbol"), "market_data", ["symbol"], unique=False
    )
    op.alter_column(
        "market_data",
        "trade_count",
        existing_type=sa.INTEGER(),
        comment="Number of trades",
        existing_comment="거래 건수",
        existing_nullable=False,
    )
    op.alter_column(
        "market_data",
        "low_price",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        comment="24-hour low price",
        existing_comment="24시간 최저가",
        existing_nullable=False,
    )
    op.alter_column(
        "market_data",
        "high_price",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        comment="24-hour high price",
        existing_comment="24시간 최고가",
        existing_nullable=False,
    )
    op.alter_column(
        "market_data",
        "volume",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        comment="24-hour trading volume",
        existing_comment="24시간 누적 거래량",
        existing_nullable=False,
    )
    op.alter_column(
        "market_data",
        "price",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        comment="Current price in KRW",
        existing_comment="현재 가격 (KRW)",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_daily_stats_date"), table_name="daily_stats")
    op.create_index(op.f("idx_daily_stats_date"), "daily_stats", ["date"], unique=True)
    op.create_unique_constraint(
        op.f("daily_stats_date_key"),
        "daily_stats",
        ["date"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_backtest_results_created_at"), table_name="backtest_results")
    # ### end Alembic commands ###
